---
version : 0.0.3
permalink: /:categories/:title
theme : fluid

base_path : '~meep'
production_url : http://sample.com

comments :
  provider : false
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light

analytics :
  provider : false
  google : 
      tracking_id : 'UA-123-12'
  getclicky :
    site_id : 

syntax :
  provider : google_prettify
  google_prettify : 
      theme: twitter-bootstrap
      linenums : true